### ISSUE TITLE
Status code 500 on /pull-mirror/new

### ISSUE THREAD

**Issue by Findus23** [Salamek/gitlab-tools#11]
Hi,

I just tried setting up gitlab-tools and it seems like everything worked correctly. 

But when I now try to add a Pull Mirror I only get an empty page with 500 after clicking on save.

Is there any way to debug what error is occuring?

Thanks for your work

**Comment by Findus23** [comment]
Turns out that this is the error that is occurring:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gitlab_tools/views/pull_mirror/index.py", line 134, in new_mirror
    if flask.request.method == 'POST' and form.validate():
  File "/usr/lib/python3/dist-packages/gitlab_tools/forms/pull_mirror.py", line 64, in validate
    check_project_visibility_in_group(self.visibility.data, self.group.data)
  File "/usr/lib/python3/dist-packages/gitlab_tools/tools/gitlab.py", line 16, in check_project_visibility_in_group
    group = get_group(group_id)
  File "/usr/lib/python3/dist-packages/gitlab_tools/tools/gitlab.py", line 47, in get_group
    return gl.groups.get(group_id)
  File "/usr/lib/python3/dist-packages/gitlab/exceptions.py", line 247, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gitlab/mixins.py", line 44, in get
    id = id.replace('/', '%2F')
AttributeError: 'NoneType' object has no attribute 'replace'
```
This seems similar to https://github.com/flask-api/flask-api/issues/65

Do you have any idea how this could be solved?

**Comment by Findus23** [comment]
If it helps you: 
I just tested it again and now I can add pull mirrors, but they fail to run, because of the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask_celery/__init__.py", line 89, in __call__
    return task_base.__call__(self, *_args, **_kwargs)
  File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask_celery/__init__.py", line 140, in wrapped
    ret_value = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gitlab_tools/tasks/gitlab_tools.py", line 45, in save_pull_mirror
    gl.groups.get(mirror.group.gitlab_id)
  File "/usr/lib/python3/dist-packages/gitlab/exceptions.py", line 247, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gitlab/mixins.py", line 44, in get
    id = id.replace('/', '%2F')
AttributeError: 'NoneType' object has no attribute 'replace'
```
which I think has the same underlying reason

**Comment by Salamek** [comment]
@Findus23 Looks like you forgot to select group for mirrored project ?
![screenshot_2018-07-22_18-06-37](https://user-images.githubusercontent.com/1226241/43047602-134ef966-8dda-11e8-9a5d-76f459b1540e.png)

(And that means i forgot to add required check for that form field...)

**Comment by Findus23** [comment]
Indeed I didn't enter a group. I'm a bit new to gitlab and don't have a group setup. Is it required?

Thanks for the help

**Comment by Salamek** [comment]
@Findus23 You should be able to mirror into your user namespace (just find your user as a group), but it looks like it is not working for some reason...
So for now i suggest to create "Mirrors" group under your account and create your mirror in there or you can wait ~4h for me to fix this new issue (I created new issue #12)

**Comment by Findus23** [comment]
Thanks, 
Using a group for all mirrors sounds like a good idea nevertheless. 
But I think I found another bug/missing feature and will report it in a separate issue.
