### ISSUE TITLE
Fingerprint error

### ISSUE THREAD

**Issue by viletay** [Salamek/gitlab-tools#24]
Hello
Using RHEL7
Install manualy, take /static/node_modules from deb package - missing here
Take error on adding fingerprint or mirror:

[pid: 29400|app: 0|req: 8/8] 192.168.38.138 () {50 vars in 1430 bytes} [Tue Jul 23 07:59:43 2019] POST /fingerprint/fingerprint-check => generated 918 bytes in 253 msecs (HTTP/1.1 200) 2 headers in 72 bytes (2 switches on core 0)
[2019-07-23 07:59:44,611] ERROR in app: Exception on /fingerprint/fingerprint-add [POST]
Traceback (most recent call last):
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/gitlab_tools/views/fingerprint/index.py", line 207, in add_hostname_fingerprint
    public_key = import_key(get_user_public_key_path(current_user, flask.current_app.config['USER']))
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/gitlab_tools/tools/crypto.py", line 43, in import_key
    return RSA.importKey(f.read())
  File "/home/gitlab-tools/venv-gitlab-tools/env/lib/python3.6/site-packages/Crypto/PublicKey/RSA.py", line 678, in importKey
    if bord(externKey[0])==0x30:
IndexError: index out of range
[pid: 29400|app: 0|req: 9/9] 192.168.38.138 () {50 vars in 1428 bytes} [Tue Jul 23 07:59:44 2019] POST /fingerprint/fingerprint-add => generated 4219 bytes in 68 msecs (HTTP/1.1 500) 2 headers in 100 bytes (1 switches on core 0)

Can you help?

**Comment by Salamek** [comment]
@viletay 
1. Do you have celery running ? You need to have these services running for background tasks to work: 
 * https://github.com/Salamek/gitlab-tools/blob/master/etc/systemd/system/gitlab-tools_celerybeat.service
 * https://github.com/Salamek/gitlab-tools/blob/master/etc/systemd/system/gitlab-tools_celeryworker.service
2. Did you run `python3 manage.py setup` after install ?
3. Does `/home/gitlab-tools/.ssh/id_rsa_USER_ID exists ? (where id is your USER ID)

**Comment by Salamek** [comment]
Closing this due to old age...
