### ISSUE TITLE
ImportError when Setting up development environment

### ISSUE THREAD

**Issue by PedroCavaleiro** [Salamek/gitlab-tools#29]
Since I use CentOS I was unable to install it using the repo. I'm trying to use from source following your [wiki](https://github.com/Salamek/gitlab-tools/wiki/Setting-up-development-enviorment)

But when I reach the `python manage.py` to test the installation I get an error the error: `ImportError: cannot import name 'ImmutableDict'`

Full Traceback
```
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from gitlab_tools.bin.gitlab_tools import main
  File "/root/gitlab-tools/gitlab_tools/bin/gitlab_tools.py", line 75, in <module>
    from gitlab_tools.application import create_app, get_config
  File "/root/gitlab-tools/gitlab_tools/application.py", line 9, in <module>
    from flask_babel import gettext
  File "/root/gitlab-tools/venv/lib/python3.6/site-packages/flask_babel/__init__.py", line 19, in <module>
    from werkzeug import ImmutableDict
ImportError: cannot import name 'ImmutableDict'
```

**Comment by Salamek** [comment]
Upgrade flask-babel to latest version by running:

`pip install --upgrade flask-babel`

inside virtualenv and try it again (and let me know if it works ok)

**Comment by PedroCavaleiro** [comment]
Thanks, it worked flawlessly
