### ISSUE TITLE
Celeryworker crash

### ISSUE THREAD

**Issue by Salamek** [Salamek/gitlab-tools#33]
```
Traceback (most recent call last):
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:   File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 382, in trace_task
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:     R = retval = fun(*args, **kwargs)
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:   File "/usr/lib/python3/dist-packages/flask_celery/__init__.py", line 89, in __call__
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:     return task_base.__call__(self, *_args, **_kwargs)
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:   File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 641, in __protected_call__
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:     return self.run(*args, **kwargs)
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:   File "/usr/lib/python3/dist-packages/celery/app/builtins.py", line 25, in backend_cleanup
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:     app.backend.cleanup()
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:   File "/usr/lib/python3/dist-packages/celery/backends/database/__init__.py", line 178, in cleanup
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]:     Task.date_done < (now - expires)).delete()
Nov 03 16:45:00 gitlab-tools gitlab-tools[343]: TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'

```

**Comment by Salamek** [comment]
Since this is Celery 4 crash, and we are using Celery 5 now, i'm closing this (code in `database/__init__.py` is completely different now)
