### ISSUE TITLE
500 Internal Server Error at pull mirror

### ISSUE THREAD

**Issue by preussal** [Salamek/gitlab-tools#45]
with Gitlab v16.6.1

When I click on Pull Mirror
500 Internal Server Error
Uh-oh you found a bug! On Email Has Been Sent to the Admins List.

With Home, Push Mirror, fingerprint everything is ok.

```
E1211 11:07:36.859 3122222 app.py:1891] Exception on /pull-mirror/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gitlab_tools/views/pull_mirror/index.py", line 116, in get_mirror
    return flask.render_template('pull_mirror.index.pull_mirror.html', pagination=pagination), 200
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/gitlab_tools/views/pull_mirror/templates/pull_mirror.index.pull_mirror.html", line 1, in <module>
    {% extends "base.html" %}
  File "/usr/lib/python3/dist-packages/gitlab_tools/templates/base.html", line 72, in <module>
    {% block body %}{% endblock %}
  File "/usr/lib/python3/dist-packages/gitlab_tools/views/pull_mirror/templates/pull_mirror.index.pull_mirror.html", line 26, in <module>
    <tr class="bg-{{item.task_results.first()|format_task_status_class}}" title="{{item.note}}">
  File "/usr/lib/python3/dist-packages/gitlab_tools/middleware.py", line 134, in format_task_status_class_filter
    }.get(task_result.taskmeta.status, 'warning')
AttributeError: 'NoneType' object has no attribute 'status'
I1211 11:07:36.861 3122222 _internal.py:122] 10.83.10.105 - - [11/Dec/2023 11:07:36] "GET /pull-mirror/ HTTP/1.1" 500 -

```

**Comment by Salamek** [comment]
Hmm not sure why metadata is empty, but i made changes in 1.4.7 to not crash in this part of code when this happens...  try to update and we will see where that gets you...

**Comment by preussal** [comment]
Problem solved 
Thank you

Try again + Update + Restart Gitlab-tools + Try again 

```
E1212 15:14:32.314 714928 app.py:1891] Exception on /pull-mirror/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gitlab_tools/views/pull_mirror/index.py", line 116, in get_mirror
    return flask.render_template('pull_mirror.index.pull_mirror.html', pagination=pagination), 200
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/gitlab_tools/views/pull_mirror/templates/pull_mirror.index.pull_mirror.html", line 1, in <module>
    {% extends "base.html" %}
  File "/usr/lib/python3/dist-packages/gitlab_tools/templates/base.html", line 72, in <module>
    {% block body %}{% endblock %}
  File "/usr/lib/python3/dist-packages/gitlab_tools/views/pull_mirror/templates/pull_mirror.index.pull_mirror.html", line 26, in <module>
    <tr class="bg-{{item.task_results.first()|format_task_status_class}}" title="{{item.note}}">
  File "/usr/lib/python3/dist-packages/gitlab_tools/middleware.py", line 134, in format_task_status_class_filter
    }.get(task_result.taskmeta.status, 'warning')
AttributeError: 'NoneType' object has no attribute 'status'
I1212 15:14:32.316 714928 _internal.py:122] 10.83.10.105 - - [12/Dec/2023 15:14:32] "GET /pull-mirror/ HTTP/1.1" 500 -
I1212 15:14:40.198 734355 _internal.py:122]  * Running on http://10.83.23.46:8081/ (Press CTRL+C to quit)
I1212 15:14:41.559 734355 _internal.py:122] 10.83.10.105 - - [12/Dec/2023 15:14:41] "GET /pull-mirror/ HTTP/1.1" 200 -
```

**Comment by Salamek** [comment]
@preussal great!, please close the issue if this is everything you needed...

**Comment by Salamek** [comment]
Well i take this as resolved then, closing...
